### ISSUE TITLE
more documentation for docker deployment

### ISSUE THREAD

**Issue by kahidna** [hotosm/osm-export-tool#297]
I tried to deploy osm-export-tool using docker.
I follow the tutorial from your <a href="https://github.com/hotosm/osm-export-tool#development-with-docker">readme</a>.
- so I clone this repository and then run 
- go to the root project directory, and run : 
```
echo "HOSTNAME=localhost" > .env
docker-compose up
```
- and I got this error messages after run `docker-compose up`:

```
Step 16/19 : RUN   python manage.py collectstatic --no-input --link   && python manage.py collectstatic -i ui\* --no-input   && mkdir /opt/static/css   && touch /opt/static/css/style.css
 ---> Running in 4f79b2ebe45f
WARNING: secret key not set - setting a default for development.
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 338, in execute
    django.setup()
  File "/usr/local/lib/python2.7/dist-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/config.py", line 94, in create
    module = import_module(entry)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/local/lib/python2.7/dist-packages/oauth2_provider/__init__.py", line 4, in <module>
    __version__ = pkg_resources.require("django-oauth-toolkit")[0].version
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 943, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 834, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (Django 1.11.15 (/usr/local/lib/python2.7/dist-packages), Requirement.parse('django>=2.0'), set(['django-oauth-toolkit']))
ERROR: Service 'base' failed to build: The command '/bin/sh -c python manage.py collectstatic --no-input --link   && python manage.py collectstatic -i ui\* --no-input   && mkdir /opt/static/css   && touch /opt/static/css/style.css' returned a non-zero code: 1
```
- I already run this command few times just like you said 
> When initializing the project, you may need to run this twice in order for the database to be initialized.

but the issue persist.  is there step(s) that I miss?

**Comment by bdon** [comment]
Hi,

The cause of this failure was that the python package django-oauth-toolkit did not have a version specified, causing it to default to a newer, incompatible version.
This has been fixed here: https://github.com/hotosm/osm-export-tool/blob/master/requirements.txt

The installation instructions have been updated and should work with Docker if your base image is Ubuntu 18.04. Documentation is here: https://github.com/hotosm/osm-export-tool/tree/master/ops/packer
